### ISSUE TITLE
Clarification on the scorer

### ISSUE THREAD

**Issue by sweta20** [amazon-science/contrastive-controlled-mt#4]
Hi,

I wanted to clarify if the following behavior is intended with the scorer.py or if it is a bug:

In [line 88](https://github.com/amazon-research/contrastive-controlled-mt/blob/main/IWSLT2022/scorer.py#L88), the accuracy is calculated with the denominator "n_matched" which is based on the **predicted** labels using the predict_formality_label function. We observed that the model can get a very high accuracy ~ 100% in scenarios where the model generates mostly neutral samples and a few samples from the desired formality style as the  "n_matched" doesn't account for NEUTRAL samples. We also found that the NEUTRAL samples could be potentially labelled with formal/informal class but are not matched with the reference annotations as the phrase matching doesn't account for punctuations, for example, "weißt du," is not matched with "weißt du".

Sample Colab: https://colab.research.google.com/drive/1u4jVlGL8KBPneBnH0_secKHI52a8JdRr?usp=sharing
Data:
[test_data.zip](https://github.com/amazon-research/contrastive-controlled-mt/files/8217484/test_data.zip)

**Comment by mnadejde** [comment]
Hi sweta20,

Thank you for pointing out the issue with phrases not being matched on account of punctuation being present in the annotated span. We will look into updating the script.

Regarding the other observation that a system may get very high accuracy while mostly outputting translations that do not mark formality, we have the following information to share:

- The metric was designed to evaluate system-level accuracy on the targeted test set which we are releasing for the shared task. All the segments in this test set have translations that mark formality. A system that does not mark formality on the majority of the targeted  test set most likely has very low translation quality and the evaluation on the generic test sets should show this.
- We have evaluated the automatic metric by comparing predicted labels against labels assigned by professional translators. This evaluation was done on the outputs produced by large-scale generic systems. We found the segment-level Precision and Recall of the metric  are reasonably high across languages (for German, `P=0.96` and `R=0.86` for Formal and `P=0.98` and `R=0.68` for Informal). Furthermore, the generic systems do mark formality in the output when translating our test sets.
- We will look into updating the metric to also output the percentage of the test set for which formality markers were identified (something like: (`ref_matched_count_FORMAL` + `ref_matched_count_INFORMAL`)/total). This will allow us to identify extreme cases. However, we will not use this additional score to rank systems.

Please include your observations on the evaluation metric in your system description paper. As this is the first time we organize the shared task we're hoping to learn from participants and improve the setup for a next edition.

**Comment by sweta20** [comment]
Thanks for the clarification and glad to know about the human evaluation! I agree that the accompanying metrics for measuring translation quality with the scorer should be able to reduce the problem. I also like the idea of reporting ref_matched_count_FORMAL + ref_matched_count_INFORMAL)/total as an additional sanity check.

**Comment by bhsu22** [comment]
Hi sweta20,

Thanks again for pointing out the issue with the punctuation. We've uploaded the testset references and haven't found any issues with punctuation being included in the annotations. At this time, we won't be updating the scoring script.
